version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: WEB-APP
    volumes:
      - .:/usr/src/app/WebApp
      - /usr/src/app/WebApp/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm start
    #command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
#    depends_on:
#      - redis
#      - postgres
#  redis:
#    container_name: redis
#    image: redis:5
#    networks:
#      - webnet
# postgres:
#    container_name: postgres
#    image: postgres:12
#    networks:
#      - webnet
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_DB: ${DB_DATABASE_NAME}
#      PG_DATA: /var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
#    volumes:
#      pgdata:

# sudo docker-compose up -d --build
#npm install -g @nestjs/cli

      